name: Publish Homey App
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  main:
    name: Publish Homey App
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Install system dependencies
        run: |
          apk add --no-cache python3 make g++ git
      
      - uses: actions/checkout@v4
      
      - name: Configure git
        run: |
          git config --global --add safe.directory /github/workspace
      
      - name: Install dependencies
        run: |
          rm -f package-lock.json
          # Install all dependencies including dev
          npm install --no-package-lock
          # Install Homey types from npm package
          npm install --save-dev homey-apps-sdk-v3-types@0.3.10
          # Install specific versions of problematic packages
          npm install --save-dev @types/node@16.18.86
          npm install --save-dev typescript@5.0.4
          npm install --save-dev eslint@7.32.0
          npm install --save-dev eslint-config-athom@3.1.5
      
      - run: npm run build
      
      - name: Validate
        uses: athombv/github-action-homey-app-validate@master
        with:
          level: publish
        
      - name: Publish
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY 