name: Publish Homey App
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  main:
    name: Publish Homey App
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          apk add --no-cache python3 make g++
      
      - name: Install dependencies
        run: |
          # First install all dependencies for build
          npm ci || npm install
          # Then remove dev dependencies for production
          npm prune --production
        
      - name: Build
        run: npm run build
        
      - name: Validate
        uses: athombv/github-action-homey-app-validate@master
        with:
          level: publish
        
      - name: Publish
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY 