name: Publish Homey App
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  main:
    name: Publish Homey App
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          apk add --no-cache python3 make g++ vips-dev
      
      - name: Install dependencies
        run: |
          # Install dependencies without package lock
          npm install --no-package-lock
          # Install sharp specifically for Alpine
          npm install --platform=linuxmusl --arch=x64 sharp
      
      - name: Build
        run: npm run build
        
      - name: Validate
        uses: athombv/github-action-homey-app-validate@master
        with:
          level: publish
        
      - name: Publish
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY 