name: Validate Homey App

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libvips-dev
      
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          npm install
          npm install sharp --ignore-scripts
          npm rebuild sharp
      
      - run: npm run build
        
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: publish 