name: Validate Homey App

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          apk add --no-cache python3 make g++
      
      - name: Install dependencies
        run: |
          npm install --no-package-lock
      
      - name: Build
        run: npm run build
        
      - name: Validate
        uses: athombv/github-action-homey-app-validate@master
        with:
          level: publish 