name: Validate Homey App

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          apk add --no-cache python3 make g++ vips-dev
      
      - name: Install dependencies
        run: |
          npm install
          npm install sharp --ignore-scripts
          npm rebuild sharp
      
      - run: npm run build
        
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified 