name: Validate Homey App

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          npm install
          npm install --platform=linuxmusl --arch=x64 sharp
      
      - run: npm run build
        
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified 