name: Validate Homey App

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            libvips-dev \
            pkg-config
            
      - name: Install dependencies
        run: |
          npm install --ignore-scripts
          npm rebuild sharp --build-from-source
          npm install homey@3.7.15 --save-exact
        env:
          SHARP_IGNORE_GLOBAL_LIBVIPS: "1"
        
      - name: Build TypeScript
        run: npm run build
        
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified 